app/Http/routes.php
<?php

Route::get(
    '/', function () {
        return redirect()->route('lead.index');
    }
);

Route::get('dashboard', function() 
{
    return view('dashboard.index');
    
})->name('dashboard');

Route::resource('lead-source', 'LeadSourceController');
Route::resource('lender', 'LenderController');
Route::resource('lender-office', 'LenderOfficeController');
Route::resource('lead-address', 'LeadAddressController');
Route::resource('appointment', 'AppointmentController');

Route::get('lead/thank-you', [
    'uses' => 'LeadController@thankYou',
    'as' => 'lead.thank-you'
]);
Route::resource('lead', 'LeadController');

Route::get('dashboard/lead-counts', [
    'uses' => 'DashboardController@getLeadSourceLeadCounts',
    'as' => 'dashboard.lead-counts',
]);

Route::get(
    'lead/summary-by-lead-source',
    ['as' => 'lead.summary_by_lead_source',
     'uses' => 'LeadController@summaryByLeadSource'
    ]
);

Route::get(
    'lead/summary-by-city',
    ['as' => 'lead.summary_by_city',
     'uses' => 'LeadController@summaryByCity'
    ]
);

app/Lead.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\LeadSource;
use DB;

class Lead extends Model
{
    protected $fillable = ['caller_number', 'city', 'state', 'caller_name', 'call_sid'];

    public function leadSource()
    {
        return $this->belongsTo('App\LeadSource');
    }

    public static function byLeadSource()
    {
        $leadsBySource
            = DB::table('leads')
            ->join('lead_sources', 'leads.lead_source_id', '=', 'lead_sources.id')
            ->select(
                DB::raw('count(1) as lead_count'),
                'lead_sources.description',
                'lead_sources.number'
            )
            ->groupBy(
                'lead_source_id',
                'lead_sources.description',
                'lead_sources.number'
            )
            ->orderBy('lead_count', 'DESC')
            ->orderBy('lead_sources.description', 'DESC')
            ->get();

        return $leadsBySource;
    }

    public static function byCity()
    {
        $leadsByCity
            = DB::table('leads')
            ->join('lead_sources', 'leads.lead_source_id', '=', 'lead_sources.id')
            ->select(DB::raw('count(1) as lead_count'), 'leads.city')
            ->groupBy('leads.city')
            ->get();

        return $leadsByCity;
    }
}

app/Models/Lead.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\LeadSource;
use App\Models\LeadAddress;

class Lead extends Model
{    
    use Phone;
    
    public function source()
    {
        return $this->hasOne(LeadSource::class, 'id', 'lead_source_id')
                ->first();
    }
    
    public function addresses()
    {
        return $this->hasMany(LeadAddress::class, 'lead_id', 'id');
    }
    
    public static function statuses()
    {
        return [
            'new' => 'New Lead',
            'confirmed' => 'Appointment Confirmed',
            'ready' => 'Ready for Loan',
            'remediate' => 'In Remediation',
        ];
    }
}

app/Http/Controllers/LeadController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\LeadSource;
use App\Models\Lender;
use App\Models\Appointment;
use App\Models\Lead;
use App\Jobs\QueuedText;

class LeadController extends Controller
{    
    public function dashboard()
    {       
       return redirect()->route('lead.index');

       // return opportunities
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $leads = Lead::all();
        
        return view('leads.index', compact('leads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $leadSources = LeadSource::getList();
        $avaliableLenders = Lender::avaliableLenders();
        $appointments = Appointment::avaliable()->orderBy('when')->get();
        
        $context = compact('leadSources', 'avaliableLenders', 'appointments');
        
        return view('leads.create', $context);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $lead = new Lead; 
        $lead->lead_source_id = $request->get('lead_source_id');
        $lead->first = $request->get('first');
        $lead->last = $request->get('last');
        $lead->name = $lead->first . ' ' . $lead->last;
        $lead->email = $request->get('email');
        $lead->number =  $request->get('phone_number');
        $lead->status = 'new';
        $lead->income = 0;
        $lead->debt = 0;
        $lead->verified = 0;
        $lead->credit_score = 0;
        $lead->ssn = 0;
        $lead->save();
        
        // Effectively, "fills" appointment.
        $appointment = Appointment::find($request->get('appointment_id'));
        $appointment->for = $lead->id;
        $appointment->save();
        
        $leadSource = $lead->source();
        $lender = $appointment->lender();
        $office = $lender->office();
        
        $context = compact('lead', 'leadSource', 'appointment', 'lender', 'office');
        
        for ($i = 1; $i < 5; $i++)
        {
            $leadText = new QueuedText($lead->number, 'leads.text' . $i, $context);
            $this->dispatch($leadText);
            $sourceText = new QueuedText($leadSource->number, 'leads.text' . $i, $context);
            $this->dispatch($sourceText);
            $lenderText = new QueuedText($lender->number, 'leads.text' . $i, $context);
            $this->dispatch($lenderText);
        }
        
        return redirect()->route('lead.thank-you');
    }
    
    public function thankYou()
    {
        return view('leads.thank-you');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $lead = Lead::find($id);

        return view('leads.show', compact('lead'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lead = Lead::find($id);        
        $statuses = Lead::statuses();
                
        return view('leads.edit', compact('statuses', 'lead'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $lead = Lead::find($id);
        $lead->status = $request->get('status');
        $lead->income = $request->get('income');
        $lead->debt = $request->get('debt');
        $lead->credit_score = $request->get('credit_score');
        $lead->verified = $request->get('verified');
        $lead->save();
        
        return redirect()->route('lead.edit', compact('id'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Lead::find($id)->delete();
        
        return redirect()->route('lead.index');
    }
}

resources/views/leads/create.blade.php
@extends('layouts.temp')

@section('content')
    <h1>Create a new lead</h1>
    <hr>
        {!! Form::open(['route' => 'lead.store']) !!}
        <div class="form-group">
            {!! Form::label('first', 'First Name:') !!}
            {!! Form::text('first') !!}
        </div>
        <div class="form-group">
            {!! Form::label('last', 'Last Name:') !!}
            {!! Form::text('last') !!}
        </div>
        <div class="form-group">
            {!! Form::label('phone_number', 'Phone Number:') !!}
            {!! Form::text('phone_number') !!}
        </div>
        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::text('email') !!}
        </div>
        <div class="form-group">
            {!! Form::label('lead_source_id', 'Lead Source:') !!}
            {!! Form::select('lead_source_id', $leadSources) !!}
        </div>
        <h3>Avaliable Appointments</h3>
        <div class="row">
            <div class="col-lg-8">
                <table class="table">
                    <thead>
                        <th>With</th>
                        <th>When</th>
                        <th></th>
                    </thead>
                    <tbody>
                        @foreach ($appointments as $appointment)
                            <tr>
                                <td> {{ $appointment->lender()->name }} </td>
                                <td> {{ $appointment->when->format('F jS - g:ia (l)') }} </td>
                                <td>
                                  {!! Form::radio('appointment_id', $appointment->id) !!}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
    </div>
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}
@stop

resources/views/leads/edit.blade.php
@extends('layouts.master')

@section('content')
    <h2>Edit a lead </h2>
    
    <h3>{{ $lead->name }}</h3>
    <h4>Referred by: {{ $lead->source()->name }}</h4>
        {!! Form::model($lead, [
            'route' => ['lead.update', $lead->id], 
            'method' => 'put'
        ]) !!}
        <div class="form-group">
            {!! Form::label('status', 'Status:') !!}
            {!! Form::select('status', $statuses, $lead->status) !!}
        </div>
        <div class="form-group">
            {!! Form::label('income', 'Income:') !!}
            {!! Form::text('income', $lead->income) !!}
        </div>
        <div class="form-group">
            {!! Form::label('debt', 'Debt:') !!}
            {!! Form::text('debt', $lead->debt) !!}
        </div>
        <div class="form-group">
            {!! Form::label('credit_score', 'Credit Score:') !!}
            {!! Form::text('credit_score', $lead->credit_score) !!}
        </div>
        <div class="form-group">
            {!! Form::label('verified', 'Verified:') !!}
            {!! Form::select('verified', [0 => 'No', 1 => 'Yes'], 
            $lead->verified) !!}
        </div>
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}
        
        <hr />
        
        <h3>Addresses</h3>
        
        <h4>Current Addresses</h4>
        <div class="row">
            <div class="col-lg-8">
                <table class="table">
                    <thead>
                        <th>Address</th>
                        <th>City</th>
                        <th>State</th>
                        <th>Postal</th>
                        <th></th>
                    </thead>
                    <tbody>
                        @foreach ($lead->addresses()->get() as $address)
                            <tr>
                                <td>{{ $address->line_one }} {{ $address->line_two }}</td>
                                <td>{{ $address->city }}</td>
                                <td>{{ $address->state }}</td>
                                <td>{{ $address->postal }}</td>
                                <td>
                                    {!! Html::link(route('lead-address.edit', $address->id),
                                    'Edit', ['class' => 'btn btn-default btn-xs']) !!}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        
        <h4>Add address</h4>
        {!! Form::open(['route' => 'lead-address.store']) !!}
        {!! Form::hidden('lead_id', $lead->id) !!}
        <div class="form-group">
            {!! Form::label('from', 'From:') !!}
            {!! Form::date('from') !!}
        </div>
        <div class="form-group">
            {!! Form::label('to', 'To:') !!}
            {!! Form::date('to') !!}
        </div>
        <div class="form-group">
            {!! Form::label('line_one', 'Address 1:') !!}
            {!! Form::text('line_one') !!}
        </div>
        <div class="form-group">
            {!! Form::label('line_two', 'Address 2:') !!}
            {!! Form::text('line_two') !!}
        </div>
        <div class="form-group">
            {!! Form::label('city', 'City:') !!}
            {!! Form::text('city') !!}
        </div>
        <div class="form-group">
            {!! Form::label('state', 'State:') !!}
            {!! Form::text('state') !!}
        </div>
        <div class="form-group">
            {!! Form::label('postal', 'Postal:') !!}
            {!! Form::text('postal') !!}
        </div>
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}
        
        <hr />
        {!! Form::open(['url' => route('lead.destroy', $lead->id),
                    'method' => 'DELETE']) !!}
        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
        {!! Form::close() !!}
@stop

resources/views/leads/index.blade.php
@extends('layouts.master')

@section('content')    
    <div class="row">
        <div class="col-lg-8">
          
            <table class="table">
                <thead>
                    <th>Name</th>
                    <th>
                      <a href="{{ route('lead.create') }}" class="btn btn-primary btn-xs">
                        Add
                      </a>
                    </th>
                </thead>
                <tbody>
                    @if (count($leads) > 0)
                        @foreach ($leads as $lead)
                            <tr>
                                <td> {{ $lead->name }} </td>
                                <td>
                                    {!! Html::link(route('lead.edit', $lead->id), 'Edit',
                                                   ['class' => 'btn btn-default btn-xs']) !!}
                                </td>
                            </tr>
                        @endforeach
                    @else
                    <td>Let's get some leads!</td>
                    @endif
                </tbody>
            </table>
            
        </div>
    </div>
@stop

resources/views/leads/show.blade.php
@extends('layouts.master')

@section('content')
    <h3>{{ $lead->name }}</h3>
    <p>Source: {{ $lead->source()->name }}</p>
    <p>Status: {{ $lead->status }}</p>
    <p>Income: {{ $lead->income }}</p>
    <p>Debt: {{ $lead->debt }}</p>
    <p>Verified: {{ $lead->verified == 1 ? "Y" : "N" }}</p>
    <p>Credit Score: {{ $lead->credit_score }}</p>
    <a href='{{ route('lead.edit', ['id' => $lead->id]) }}'>Edit</a>
@stop

resources/views/leads/thank-you.blade.php
@extends('layouts.temp')

@section('content')
<div id="page"></div>
@stop

@section('scripts')
<script>
$( document ).ready(function() {
    var count = 5;
    var countdown = setInterval(function(){
      $("#page").html(
        "<h3>Thank you</h3>" + 
        "<h4>We'll take you back in " + count + " seconds.</h4>"
      );
      if (count === 0) {
        clearInterval(countdown);
        window.open("{{ route('lead.create') }}", "_self");
      }
      count--;
    }, 1000);
});
</script>
@stop