app/Http/routes.php
<?php

Route::get(
    '/', function () {
        return redirect()->route('lead.index');
    }
);

Route::get('dashboard', function() 
{
    return view('dashboard.index');
    
})->name('dashboard');

Route::resource('lead-source', 'LeadSourceController');
Route::resource('lender', 'LenderController');
Route::resource('lender-office', 'LenderOfficeController');
Route::resource('lead-address', 'LeadAddressController');
Route::resource('appointment', 'AppointmentController');

Route::get('lead/thank-you', [
    'uses' => 'LeadController@thankYou',
    'as' => 'lead.thank-you'
]);
Route::resource('lead', 'LeadController');

Route::get('dashboard/lead-counts', [
    'uses' => 'DashboardController@getLeadSourceLeadCounts',
    'as' => 'dashboard.lead-counts',
]);

Route::get(
    'lead/summary-by-lead-source',
    ['as' => 'lead.summary_by_lead_source',
     'uses' => 'LeadController@summaryByLeadSource'
    ]
);

Route::get(
    'lead/summary-by-city',
    ['as' => 'lead.summary_by_city',
     'uses' => 'LeadController@summaryByCity'
    ]
);

app/Models/Lender.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\LenderOffice;

class Lender extends Model
{
    use Phone;
    
    protected $table = 'lenders';
    
    protected $guarded = [];
    
    public function office()
    {
        return $this->hasOne(LenderOffice::class, 'id', 'office_id')->first();
    }
    
    public static function avaliableLenders()
    {
        $lenders = static::all();
        $list = [];
        
        foreach ($lenders as $lender)
        {
            $list[$lender->id] = $lender->name;
        }
        
        return $list;
    }
}

app/Http/Controllers/LenderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Lender;
use App\Models\LenderOffice;

class LenderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lenders = Lender::all();
        
        return view('lenders.index', compact('lenders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $offices = LenderOffice::getList();
        
        return view('lenders.create', compact('offices'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $lender = new Lender($request->all());
        
        $lender->name = $lender->first . ' ' . $lender->last;
        $lender->save();
        
        return redirect()->route('lender.show', ['id' => $lender->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $lender = Lender::find($id);
        
        return view('lenders.show', compact('lender'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lender = Lender::find($id);
        $offices = LenderOffice::getList();
        
        return view('lenders.edit', compact('lender', 'offices'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $lender = Lender::find($id)->fill($request->all())->save();
        
        return redirect()->route('lender.show', compact('id'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Lender::find($id)->delete();
        
        return redirect()->route('lender.index');
    }
}

resources/views/lenders/create.blade.php
@extends('layouts.master')

@section('content')
    <h1>Add new Lender</h1>
    <hr>
        {!! Form::open(['route' => 'lender.store']) !!}
        <div class="form-group">
            {!! Form::label('first', 'First Name:') !!}
            {!! Form::text('first') !!}
        </div>
        <div class="form-group">
            {!! Form::label('last', 'Last Name:') !!}
            {!! Form::text('last') !!}
        </div>
        <div class="form-group">
            {!! Form::label('nmls_id', 'National Mortgage Lender ID:') !!}
            {!! Form::text('nmls_id') !!}
        </div>
        <div class="form-group">
            {!! Form::label('banker_id', 'Banker License Number:') !!}
            {!! Form::text('banker_id') !!}
        </div>
        <div class="form-group">
            {!! Form::label('office_id', 'Office:') !!}
            {!! Form::select('office_id', $offices) !!}
        </div>
        <div class="form-group">
            {!! Form::label('number', 'Phone Number:') !!}
            {!! Form::text('number') !!}
        </div>
        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::text('email') !!}
        </div>
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}
@stop

resources/views/lenders/edit.blade.php
@extends('layouts.master')

@section('content')
    <h1>Edit Lender</h1>
    <hr>
        {!! Form::model($lender, [
        'route' => ['lender.update', $lender->id], 
        'method' => 'PUT'
        ]) !!}
        <div class="form-group">
            {!! Form::label('first', 'First:') !!}
            {!! Form::text('first') !!}
        </div>
        <div class="form-group">
            {!! Form::label('last', 'Last:') !!}
            {!! Form::text('last') !!}
        </div>
        <div class="form-group">
            {!! Form::label('nmls_id', 'National Mortgage Lender ID:') !!}
            {!! Form::text('nmls_id') !!}
        </div>
        <div class="form-group">
            {!! Form::label('banker_id', 'Banker License Number:') !!}
            {!! Form::text('banker_id') !!}
        </div>
        <div class="form-group">
            {!! Form::label('office_id', 'Office:') !!}
            {!! Form::select('office_id', $offices, $lender->office_id) !!}
        </div>
        <div class="form-group">
            {!! Form::label('number', 'Phone:') !!}
            {!! Form::text('number') !!}
        </div>
        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::text('email') !!}
        </div>
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}

    {!! Form::open(['url' => route('lender.destroy', $lender->id),
                    'method' => 'DELETE']) !!}
    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
    {!! Form::close() !!}
@stop

resources/views/lenders/index.blade.php
@extends('layouts.master')

@section('content')
    <h3>Lenders</h3>
    <div class="row">
        <div class="col-lg-8">
            <table class="table">
                <thead>
                    <th>Name</th>
                    <th>
                      <a href="{{ route('lender.create') }}" class="btn btn-primary btn-xs">
                        Add
                      </a>
                    </th>
                </thead>
                <tbody>
                    @foreach ($lenders as $lender)
                        <tr>
                            <td> {{ $lender->name }} </td>
                            <td>
                                {!! Html::link(route('lender.edit', $lender->id), 'Edit',
                                               ['class' => 'btn btn-default btn-xs']) !!}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

resources/views/lenders/show.blade.php
@extends('layouts.master')

@section('content')
    <h3>{{ $lender->id }}</h3>
    <p>First: {{ $lender->first }}</p>
    <p>Last: {{ $lender->last }}</p>
    <p>Email: {{ $lender->email }}</p>
    <p>Number: {{ $lender->number }}</p>
    <a href='{{ route('lender.edit', ['id' => $lender->id]) }}'>Edit</a>
@stop