app/Http/routes.php
<?php

Route::get(
    '/', function () {
        return redirect()->route('lead.index');
    }
);

Route::get('dashboard', function() 
{
    return view('dashboard.index');
    
})->name('dashboard');

Route::resource('lead-source', 'LeadSourceController');
Route::resource('lender', 'LenderController');
Route::resource('lender-office', 'LenderOfficeController');
Route::resource('lead-address', 'LeadAddressController');
Route::resource('appointment', 'AppointmentController');

Route::get('lead/thank-you', [
    'uses' => 'LeadController@thankYou',
    'as' => 'lead.thank-you'
]);
Route::resource('lead', 'LeadController');

Route::get('dashboard/lead-counts', [
    'uses' => 'DashboardController@getLeadSourceLeadCounts',
    'as' => 'dashboard.lead-counts',
]);

Route::get(
    'lead/summary-by-lead-source',
    ['as' => 'lead.summary_by_lead_source',
     'uses' => 'LeadController@summaryByLeadSource'
    ]
);

Route::get(
    'lead/summary-by-city',
    ['as' => 'lead.summary_by_city',
     'uses' => 'LeadController@summaryByCity'
    ]
);

app/LeadSource.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Lead;

class LeadSource extends Model
{
    protected $fillable = ['number', 'forwarding_number', 'description'];

    public function leads()
    {
        return $this->hasMany('App\Lead');
    }
}

app/Models/LeadSource.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DB;

class LeadSource extends Model
{
    use Phone;
    
    protected $table = 'lead_source';
    
    protected $guarded = [];
    
    public static function getList()
    {
        $leads = static::all();
        $list = [];
        
        foreach ($leads as $lead)
        {
            $list[$lead->id] = $lead->name;
        }
        
        return $list;
    }
    
    /**
     * Get the amount of leads each source provides
     * 
     * @return array
     */
    public static function getLeadCounts()
    {
        return DB::table('leads')
               ->join('lead_source', 'leads.lead_source_id', '=', 'lead_source.id')
               ->select(DB::raw('count(*) as count'),'lead_source.name')
               ->groupBy('lead_source.name')
               ->get();
    }
}

app/Http/Controllers/LeadSourceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\LeadSource;

class LeadSourceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $leadSources = LeadSource::all();
        
        return view('lead_sources.index', compact('leadSources'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        
        return view('lead_sources.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $leadSource = new LeadSource($request->all());
        $leadSource->name = $leadSource->first . ' ' . $leadSource->last;
        $leadSource->preffered_contact = 'text';
        $leadSource->save();
        
        $id = $leadSource->id;
        return redirect()->route('lead-source.show', compact('id'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $leadSource = LeadSource::find($id);
        
        return view('lead_sources.show', compact('leadSource'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $leadSource = LeadSource::find($id);
        
        return view('lead_sources.edit', compact('leadSource'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $leadSource = LeadSource::find($id);
        $leadSource->fill($request->all());
        $leadSource->save();
        
        return redirect()->route('lead-source.show', compact('id'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        LeadSource::find($id)->delete();
        
        return redirect()->route('lead-source.index');
    }
}

resources/views/lead_sources/create.blade.php
@extends('layouts.master')

@section('content')
    <h1>Create a new lead source</h1>
    <hr>
        {!! Form::open(['route' => 'lead-source.store']) !!}
        <div class="form-group">
            {!! Form::label('first', 'First Name:') !!}
            {!! Form::text('first') !!}
        </div>
        <div class="form-group">
            {!! Form::label('last', 'Last Name:') !!}
            {!! Form::text('last') !!}
        </div>
        <div class="form-group">
            {!! Form::label('number', 'Phone Number:') !!}
            {!! Form::text('number') !!}
        </div>
        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::text('email') !!}
        </div>
                <div class="form-group">
            {!! Form::label('title', 'Title:') !!}
            {!! Form::text('title') !!}
        </div>
        <div class="form-group">
            {!! Form::label('affiliation', 'Affiliation:') !!}
            {!! Form::text('affiliation') !!}
        </div>
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}
@stop

resources/views/lead_sources/edit.blade.php
@extends('layouts.master')

@section('content')
    <h1>Edit a lead source</h1>
    <hr>
    <h3>{{$leadSource->name}}</h3>
            <hr>
        {!! Form::open(['url' => route('lead-source.update', ['id' => $leadSource->id]), 
                        'method' => 'put']) !!}
        <div class="form-group">
            {!! Form::label('title', 'Title:') !!}
            {!! Form::text('title', $leadSource->title) !!}
        </div>
        <div class="form-group">
            {!! Form::label('affiliation', 'Affiliation:') !!}
            {!! Form::text('affiliation', $leadSource->affiliation) !!}
        </div>
        <div class="form-group">
            {!! Form::label('number', 'Phone Number:') !!}
            {!! Form::text('number', $leadSource->number) !!}
        </div>
        <div class="form-group">
            {!! Form::label('email', 'E-mail:') !!}
            {!! Form::text('email', $leadSource->email) !!}
        </div>
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}

    {!! Form::open(['url' => route('lead-source.destroy', $leadSource->id),
                    'method' => 'DELETE']) !!}
    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
    {!! Form::close() !!}
@stop

resources/views/lead_sources/index.blade.php
@extends('layouts.master')

@section('content')
<h3>Lead sources</h3>
<div class="row">
    <div class="col-lg-8">
        <table class="table">
            <thead>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Title</th>
                <th>Affiliation</th>
                <th>
                  <a href="{{ route('lead-source.create') }}" class="btn btn-primary btn-xs">
                    Add
                  </a>
                </th>
            </thead>
            <tbody>
                @foreach ($leadSources as $leadSource)
                    <tr>
                        <td> {{ $leadSource->first }} </td>
                        <td> {{ $leadSource->last }} </td>
                        <td> {{ $leadSource->title }} </td>
                        <td> {{ $leadSource->affiliation }} </td>
                        <td>
                            {!! Html::link(route('lead-source.edit', $leadSource->id), 'Edit',
                                           ['class' => 'btn btn-default btn-xs']) !!}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@stop

resources/views/lead_sources/show.blade.php
@extends('layouts.master')

@section('content')
<h3>{{$leadSource->name}}</h3>
<p>Title: {{$leadSource->title}}</p>
<p>Affiliation: {{$leadSource->affiliation}}</p>
<p>Number: {{$leadSource->number}}</p>
<a href='{{route('lead-source.edit', ['id' => $leadSource->id])}}'>Edit</a>
@stop