app/Http/routes.php
<?php

Route::get(
    '/', function () {
        return redirect()->route('lead.index');
    }
);

Route::get('dashboard', function() 
{
    return view('dashboard.index');
    
})->name('dashboard');

Route::resource('lead-source', 'LeadSourceController');
Route::resource('lender', 'LenderController');
Route::resource('lender-office', 'LenderOfficeController');
Route::resource('lead-address', 'LeadAddressController');
Route::resource('appointment', 'AppointmentController');

Route::get('lead/thank-you', [
    'uses' => 'LeadController@thankYou',
    'as' => 'lead.thank-you'
]);
Route::resource('lead', 'LeadController');

Route::get('dashboard/lead-counts', [
    'uses' => 'DashboardController@getLeadSourceLeadCounts',
    'as' => 'dashboard.lead-counts',
]);

Route::get(
    'lead/summary-by-lead-source',
    ['as' => 'lead.summary_by_lead_source',
     'uses' => 'LeadController@summaryByLeadSource'
    ]
);

Route::get(
    'lead/summary-by-city',
    ['as' => 'lead.summary_by_city',
     'uses' => 'LeadController@summaryByCity'
    ]
);

resources/views/layouts/master.blade.php
<!doctype html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="{{ asset('css/main.css') }}" rel="stylesheet">
        <title>@yield('title', 'Lead Pipeline')</title>
    </head>
    <body>
        <div class="container-fluid">
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Lead Pipeline</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
                </button>
            </div>
            <div class="collapse navbar-collapse" id="main-navbar">
                <ul class="nav navbar-nav">
                    <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ route('lead.index') }}">Leads</a></li>
                </ul>
                <ul class="nav navbar-nav">
                      <li><a href="{{ route('lead-source.index') }}">Lead Sources</a></li>
                </ul>
                <ul class="nav navbar-nav">
                      <li><a href="{{ route('lender.index') }}">Lenders</a></li>
                </ul>
                <ul class="nav navbar-nav">
                      <li><a href="{{ route('lender-office.index') }}">Mortgage Offices</a></li>
                </ul>
                <ul class="nav navbar-nav">
                      <li><a href="{{ route('appointment.index') }}">Appointments</a></li>
                </ul>
            </div>
        </nav>
        <div class="errors">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        @yield('content')
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        @yield('scripts')
        </div>
    </body>
</html>

resources/views/layouts/temp.blade.php
<!doctype html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        @yield('meta')
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="{{ asset('css/main.css') }}" rel="stylesheet">
        <title>@yield('title', 'Lead Pipeline')</title>
    </head>
    <body>
        <div class="container-fluid">
          <div class="row">
            <nav class="navbar navbar-default">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Lead Pipeline</a>
                </div>
            </nav>
            <div class="errors">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
            @yield('content')
            <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
            <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
            @yield('scripts')
          </div>
        </div>
    </body>
</html>